baseURL = 'https://example.org/'
languageCode = 'en-us'
[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false

[params]
doNotLoadAnimations = true
contentratio = 0.64
title = "Salut, c'est Quentin"
author = 'Quentin | Toofi'
profilePicture = "images/profile.jpg"
description = """
On m'appelle aussi Toofi
J'aime le code, la musique, l'IA générative et le jeu vidéo
"""

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/herpoelquentin/"
[[params.socialIcons]]
icon = "fa-brands fa-twitter"
title = "Twitter"
url = "https://www.linkedin.com/in/herpoelquentin/"
[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:qhentin@gmail.com"
[[params.socialIcons]]
icon = "fa-brands fa-spotify"
title = "Youtube"
url = "https://open.spotify.com/user/116783269"
[[params.socialIcons]]
icon = "fa-brands fa-twitch"
title = "Twitch"
url = "https://www.twitch.tv/toofi__"
[[params.socialIcons]]
icon = "fa-brands fa-youtube"
title = "Youtube"
url = "https://www.youtube.com/channel/UCSyCKD8oTm1v2ZiZ0yNfzpw"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
  